### ISSUE TITLE
add @orbeckst to maintainers

### ISSUE THREAD

**Issue by orbeckst** [conda-forge/gromacswrapper-feedstock#4]
### Comment:

@njzjz can you please add me to maintainers so that I can help with getting packages out quickly (eg for 0.9.0 https://github.com/Becksteinlab/GromacsWrapper/issues/281 )

(For context: I am the primary developer of GromacsWrapper https://github.com/Becksteinlab/GromacsWrapper )

**Comment by njzjz** [comment]
@conda-forge-admin, please add user @orbeckst

**Comment by orbeckst** [comment]
Thank you. I agree to be a maintainer on the feedstock.
